title: "Shilpita Biswas"
email: biswas.shilpita@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My MLH Journey
baseurl: "/" 
url: "/MLH-Portfolio/" 
twitter_username: shilpita_biswas
github_username:  sh-biswas

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
